/*SELECT
'ALTER TABLE '||S.SCHEMANAME||'.'||T.TABLENAME||' DROP CONSTRAINT '||C.CONSTRAINTNAME||';'
FROM
    SYS.SYSCONSTRAINTS C,
    SYS.SYSSCHEMAS S,
    SYS.SYSTABLES T
WHERE
    C.SCHEMAID = S.SCHEMAID
AND
    C.TABLEID = T.TABLEID
AND
S.SCHEMANAME = 'APP'
UNION
SELECT 'DROP TABLE ' || schemaname ||'.' || tablename || ';'
FROM SYS.SYSTABLES
INNER JOIN SYS.SYSSCHEMAS ON SYS.SYSTABLES.SCHEMAID = SYS.SYSSCHEMAS.SCHEMAID
where schemaname='APP';*/


DROP VIEW APP.EMP_DETAILS_VIEW;
DROP SEQUENCE LOCATIONS_SEQ RESTRICT;
DROP SEQUENCE DEPARTMENTS_SEQ RESTRICT;
DROP SEQUENCE EMPLOYEES_SEQ RESTRICT;
ALTER TABLE APP.LOCATIONS DROP CONSTRAINT LOC_C_ID_FK;
ALTER TABLE APP.COUNTRIES DROP CONSTRAINT COUNTR_REG_FK;
ALTER TABLE APP.EMPLOYEES DROP CONSTRAINT EMP_DEPT_FK;
ALTER TABLE APP.JOB_HISTORY DROP CONSTRAINT JHIST_DEPT_FK;
ALTER TABLE APP.DEPARTMENTS DROP CONSTRAINT DEPT_LOC_FK;
ALTER TABLE APP.DEPARTMENTS DROP CONSTRAINT DEPT_MGR_FK;
ALTER TABLE APP.EMPLOYEES DROP CONSTRAINT EMP_MANAGER_FK;
ALTER TABLE APP.JOB_HISTORY DROP CONSTRAINT JHIST_EMP_FK;
ALTER TABLE APP.EMPLOYEES DROP CONSTRAINT EMP_JOB_FK;
ALTER TABLE APP.JOB_HISTORY DROP CONSTRAINT JHIST_JOB_FK;
ALTER TABLE APP.EMPLOYEES DROP CONSTRAINT EMP_EMAIL_UK;
ALTER TABLE APP.EMPLOYEES DROP CONSTRAINT EMP_SALARY_MIN;
ALTER TABLE APP.JOB_HISTORY DROP CONSTRAINT JHIST_DATE_INTERVAL;
ALTER TABLE APP.COUNTRIES DROP CONSTRAINT COUNTRY_C_ID_PK;
ALTER TABLE APP.DEPARTMENTS DROP CONSTRAINT DEPT_ID_PK;
ALTER TABLE APP.EMPLOYEES DROP CONSTRAINT EMP_EMP_ID_PK;
ALTER TABLE APP.JOBS DROP CONSTRAINT JOB_ID_PK;
ALTER TABLE APP.JOB_HISTORY DROP CONSTRAINT JHIST_EMP_ID_ST_DATE_PK;
ALTER TABLE APP.LOCATIONS DROP CONSTRAINT LOC_ID_PK;
ALTER TABLE APP.REGIONS DROP CONSTRAINT REG_ID_PK;
DROP TABLE APP.COUNTRIES;
DROP TABLE APP.DEPARTMENTS;
DROP TABLE APP.EMPLOYEES;
DROP TABLE APP.JOBS;
DROP TABLE APP.JOB_HISTORY;
DROP TABLE APP.LOCATIONS;
DROP TABLE APP.REGIONS;
COMMIT;